export const  POLLINGRESULTS_LIST_REQUEST = 'POLLINGRESULTS_LIST_REQUEST'
export const  POLLINGRESULTS_LIST_SUCCESS = 'POLLINGRESULTS_LIST_SUCCESS'
export const  POLLINGRESULTS_LIST_FAIL = 'POLLINGRESULTS_LIST_FAIL'

export const  POLLINGRESULTS_DETAILS_REQUEST = 'POLLINGRESULTS_DETAILS_REQUEST'
export const  POLLINGRESULTS_DETAILS_SUCCESS = 'POLLINGRESULTS_DETAILS_SUCCESS'
export const  POLLINGRESULTS_DETAILS_FAIL = 'POLLINGRESULTS_DETAILS_FAIL'



export const  POLLINGRESULTS_CREATE_REQUEST = 'POLLINGRESULTS_CREATE_REQUEST'
export const  POLLINGRESULTS_CREATE_SUCCESS = 'POLLINGRESULTS_CREATE_SUCCESS'
export const  POLLINGRESULTS_CREATE_FAIL = 'POLLINGRESULTS_CREATE_FAIL'
export const  POLLINGRESULTS_CREATE_RESET = 'POLLINGRESULTS_CREATE_RESET'


export const POLLINGRESULTS_LIST_MY_REQUEST='POLLINGRESULTS_LIST_MY_REQUEST'
export const POLLINGRESULTS_LIST_MY_SUCCESS='POLLINGRESULTS_LIST_MY_SUCCESS'
export const POLLINGRESULTS_LIST_MY_FAIL='POLLINGRESULTS_LIST_MY_FAIL'
export const POLLINGRESULTS_LIST_MY_RESET='POLLINGRESULTS_LIST_MY_RESET'

